config/routes.rb
OnlineStore::Application.routes.draw do
  # Devise authenticated routes
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
    controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # Devise Login
  # as :user do
  #   get 'login' => 'devise/registrations#new', :as => 'new_user_registration'
  # end

  # Devise Scopes
  devise_scope :user do

    # Authenticated root
    authenticated :user do
      root :to => 'products#index', as: :authenticated_root
    end

    # Unauthenticated root
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end

    # Omniauth sign_out
    # delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  authenticate :user do
    resources :users, only: [:show, :edit] do
      get 'shipping_detail', to: 'users#shipping_detail', as: :shipping_detail
      resources :addresses
    end
  end

  resources :products do

  end

  get 'inventory', to: 'products#inventory', as: :inventory

  resources :order_items

  resources :transactions, only: [:new, :create]
  resources :purchases, only: [:show]
  resource :cart, only: [:show]

  namespace :admin do
    resources :users
    # resources :addresses
    resources :categories
    # resources :credit_cards
    resources :orders
    resources :order_items
    resources :products
    resources :purchases
    # resources :shippers
    # resources :suppliers

    root to: "users#index"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [ :google_oauth2 ]

  # Attributes
  # attr_accessible :first_name, :last_name, :phone, :email, :password, :password_confirmation, :remember_me, :braintree_customer_id
  attr_accessor :password, :password_confirmation

  # Associations
  has_many :credit_cards
  has_many :purchases
  has_many :orders, through: :purchases
  has_many :addresses, as: :addressable

  # Validations
  validates_presence_of :email, :password, on: :create
  validates :password, on: :create, confirmation: true
  validates :password, on: :update, confirmation: false, allow_blank: true
  # Image Validations
  has_attached_file :avatar, default_url: 'defaults/avatars/:style/missing_avatar.png'
  validates_attachment :avatar, size: { in: 0..1.megabytes }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  # Omniauth Methods
  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(:email => data["email"]).first
    unless user
      user = User.create(first_name: data["name"],
                         email: data["email"],
                         password: Devise.friendly_token[0,20]
                        )
    end
    user
  end

  # Braintree Methods
  def has_payment_info?
    braintree_customer_id
  end

  def braintree_data
    Braintree::Customer.find(braintree_customer_id)
  end

  def has_shipping_address?
    addresses.find_by_address_type('ShippingAddress')
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def edit
  end

  def shipping_detail
    # Purchase.find_by_status('purchased')
    @shipping_order = current_user.orders.find_by_status('purchased')
    @product = OrderItem.find_by_status('purchased').product
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/users/shipping_detail.html.erb
<div class='large-12'>
  <div class='large-6 column'>
    <h2><%= params[:controller].titleize %></h2>
  </div>
  <hr>
</div>

<div class='large-12'>
  <div class='medium-8 large-7 small-centered columns'>
    <div class='medium-4'>
      <div class=''>
        <%= image_tag(@product.image.url, class: 'avatar-round-square') %>

      </div>
      </div>
      <div class='medium-4'>
        <%= @shipping_order %>
      </div>
    </div>

    <br>
    <div class='warning progress radius'>
      <div class='progress-meter' style="width: 50%"></div>
      <%= tag(:span, class: '', style: 'width: #{proj.completePercent}%') %>
      <br />
      <h5><small><%# <%= proj.completePercent %></small></h5>
    </div>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class='large-12'>
  <div class='large-6 column'>
    <h2><%= params[:controller].titleize %></h2>
  </div>
  <hr>
</div>

<div class='large-12'>
  <div class='medium-8 large-7 small-centered columns'>
    <div class='callout large'>
      <%= image_tag(current_user.avatar.url(:large), class: 'avatar-round-square') %>
    </div>

    <hr>
    <div class=''>
      <ul class='vertical medium-horizontal expanded menu text-center'>
        <li>
          <div class='stat'>
            <%= current_user.purchases.count %>
            <%= label_tag :order_items %>
          </div>
        </li>
        <li>
          <div class='stat'>
            <%= current_user.purchases.count %>
            <%= label_tag :purchases %>
          </div>
        </li>
        <li>
          <div class='stat'>
            <%= current_user.purchases.count %>
            <%= label_tag :purchases %>
          </div>
        </li>
      </ul>
    </div>
    <hr>

    <div class=''>
      <ul class='tabs' data-tabs id='profile-tabs'>
        <li class='tabs-title is-active'><a href='#profile-panel' aria-selected-'true'>Profile</a></li>
        <li class='tabs-title'><a href='#address-panel'>Addresses</a></li>
        <li class='tabs-title'><a href='#purchases-panel'>Purchases</a></li>
      </ul>

      <div class='tabs-content' data-tabs-content='profile-tabs'>
        <div class='tabs-panel is-active' id='profile-panel'>
          Email: <%= current_user.email %>
          <hr>
          <%= link_to 'Change your Password', edit_user_registration_path, class: 'button alert' %>
          <%= link_to 'Add Product', new_product_path, class: 'button' %>
        </div>
        <div class='tabs-panel' id='address-panel'>
          <%= render partial: 'addresses/addresses', locals: { addressable: current_user } %>
          <%= render partial: 'addresses/form', locals: { addressable: current_user } %>
        </div>
        <div class='tabs-panel' id='purchases-panel'>
          <table class='stack hover'>
            <thead>
              <tr>
                <th>Id</th>
                <th>Status</th>
                <th>Other</th>
                <th></th>
              </tr>
            </thead>
            <% current_user.purchases.each do |purchase| %>
            <tbody>
              <tr>
                <td><%= purchase.id %></td>
                <td><%= purchase.status %></td>
                <td><%= purchase.status %></td>
                <td><%= link_to 'Receipt', purchase_path(purchase, format: :pdf) %></td>
              </tr>
            </tbody>
          <% end %>
          </table>
        </div>
      </div>
    </div>

  </div>
</div>