config/routes.rb
OnlineStore::Application.routes.draw do
  # Devise authenticated routes
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
    controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # Devise Login
  # as :user do
  #   get 'login' => 'devise/registrations#new', :as => 'new_user_registration'
  # end

  # Devise Scopes
  devise_scope :user do

    # Authenticated root
    authenticated :user do
      root :to => 'products#index', as: :authenticated_root
    end

    # Unauthenticated root
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end

    # Omniauth sign_out
    # delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  authenticate :user do
    resources :users, only: [:show, :edit] do
      get 'shipping_detail', to: 'users#shipping_detail', as: :shipping_detail
      resources :addresses
    end
  end

  resources :products do

  end

  get 'inventory', to: 'products#inventory', as: :inventory

  resources :order_items

  resources :transactions, only: [:new, :create]
  resources :purchases, only: [:show]
  resource :cart, only: [:show]

  namespace :admin do
    resources :users
    # resources :addresses
    resources :categories
    # resources :credit_cards
    resources :orders
    resources :order_items
    resources :products
    resources :purchases
    # resources :shippers
    # resources :suppliers

    root to: "users#index"
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/views/carts/_add_to_cart.html.erb
<div class=''>

  <div class=''>
    <%= form_for order_item, remote: true do |f| %>
      <h6 class=''><span style='color: green'><%= number_to_currency product.price %></span></h6>
      <div class=''>
        <div class=''>
          <%= f.number_field :quantity, value: 1, min: 1, class: ''  %>

        </div>
        <div class=''>
          <div class=''>
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: 'button expanded' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/carts/show.html.erb
<div class='large-12'>
  <div class='large-6 column'>
    <h2><%= params[:controller].titleize %></h2>
  </div>
  <br>
</div>

<div id='cart' class='small-10 medium-8 large-8 column text-center'>
  <div class='text-center'>
    <p class=''> You've selected <span class='cart-count'><%= current_order.cart_count %></span> products</p>
      <hr>
  </div>

  <% @order_items.each do |order_item|%>
    <div class='large-12 cart-row'>
      <div class='column large-2 text-center radius-left'>
        <%= link_to order_item.product do %>
          <%= image_tag order_item.product.image, class: 'radius-left' %>
        <% end %>
      </div>
      <div class='column large-7 text-center top-aligned'>
        <p class=''> <%= order_item.product.name %> </p>
        <p class=''> <%= order_item.quantity %> </p>
      </div>
      <div class='column large-3 text-center radius-right'>
        <%= link_to "", remote: true, data: { url: order_item_path(order_item) } do %>
          <i class='fi-x right'></i>
        <% end %>
        <h4 class='text-aligned'><%= number_to_currency order_item.total_price %></h4>
      </div>
    </div>
  <% end %>

</div>

<div class='small-2 medium-4 large-4 column text-center'>
  Your Total: <span class='cart-total'><%= current_order.cart_total %></span>
  <hr>
  Subtotal: <span class='cart-subtotal'><%# <%= current_order.cart_subtotal %></span>
  <br>
  Shipping: <span class='cart-shipping-cost'><%# <%= current_order.cart_shipping_costs %></span>
  <br>
  Taxes: <span class='cart-taxes'><%# <%= current_order.cart_taxes %></span>
  <br>
  <%= link_to "Checkout", new_transaction_path, class: 'button large success hollow checkout' unless current_order.order_items.blank? %>
</div>