config/routes.rb
OnlineStore::Application.routes.draw do
  # Devise authenticated routes
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
    controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # Devise Login
  # as :user do
  #   get 'login' => 'devise/registrations#new', :as => 'new_user_registration'
  # end

  # Devise Scopes
  devise_scope :user do

    # Authenticated root
    authenticated :user do
      root :to => 'products#index', as: :authenticated_root
    end

    # Unauthenticated root
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end

    # Omniauth sign_out
    # delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  authenticate :user do
    resources :users, only: [:show, :edit] do
      get 'shipping_detail', to: 'users#shipping_detail', as: :shipping_detail
      resources :addresses
    end
  end

  resources :products do

  end

  get 'inventory', to: 'products#inventory', as: :inventory

  resources :order_items

  resources :transactions, only: [:new, :create]
  resources :purchases, only: [:show]
  resource :cart, only: [:show]

  namespace :admin do
    resources :users
    # resources :addresses
    resources :categories
    # resources :credit_cards
    resources :orders
    resources :order_items
    resources :products
    resources :purchases
    # resources :shippers
    # resources :suppliers

    root to: "users#index"
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  respond_to :html, :js, :json
  before_action :authenticate_user!
  before_action :check_cart!, :new_purchase, #:check_for_addresses
  # helper_method :process_order

  def new
    @client_token = generate_client_token
  end

  def create
    unless current_user.has_payment_info?
      @result = Braintree::Transaction.sale(
        amount: current_order.cart_total,
        payment_method_nonce: params[:payment_method_nonce],
        customer: {
          first_name: params[:first_name],
          last_name: params[:last_name],
          email: current_user.email
        },
        # shipping_address: {
        #   street_address: @address.address1,
        #   location: @address.city,
        #   region: @address.state,
        #   postal_code: @address.postal_code
        # },
        options: {
          store_in_vault_on_success: true
        }
      )
    else
      @result = Braintree::Transaction.sale(
        amount: current_order.cart_total,
        # shipping: current_user.has_shipping_address?,
        payment_method_nonce: params[:payment_method_nonce])
    end

    if @result.success?
      current_user.update_attributes(braintree_customer_id: @result.transaction.customer_details.id) unless current_user.has_payment_info?
      @purchase.save
      process_order
      redirect_to user_shipping_detail_path(current_user), flash: { notice: "Transaction Successful" }
    else
      flash[:alert] = @result.errors
      generate_client_token
      render :new
    end
  end

  private

  def generate_client_token
    if current_user.has_payment_info?
      Braintree::ClientToken.generate(customer_id: current_user.braintree_customer_id)
    else
      Braintree::ClientToken.generate
    end
  end

  def process_order
    @order = current_order
    @order.success
    @order = Order.create(user: current_user)
    session[:order_id] = @order.id
    # current_order.success
    # current_order = Order.new(user: current_user) if current_order.status?('purchased')
  end

  def check_for_addresses
    unless current_user.has_shipping_address?
      @address = Address.find_or_create_by(
        addressable_id: current_user.id,
        address_type: 'ShippingAddress'
      )
    end
  end

  def check_cart!
    if current_order.order_items.blank?
      redirect_to cart_path, alert: "Please add some items"
    end
  end

  def new_purchase
    @purchase = Purchase.new(
      user_id: current_user.id,
      order_id: current_order.id
    )
  end
end

app/views/transactions/_customer_form.html.erb
<p>Please enter your personal info:</p>
<div class='form-field-border'>
  <%= text_field_tag :first_name, '',placeholder: "First Name", class: 'form-field radius' %>
</div>
<div class='form-field-border'>
  <%= text_field_tag :last_name, '',placeholder: "Last Name", class: 'form-field radius' %>
</div>
<div class='form-field-border'>
  <%= text_field_tag :phone, '',placeholder: "Phone", class: 'form-field radius' %>
</div>

app/views/transactions/new.html.erb
<div class='large-12'>
  <div class='large-6 column'>
    <h2><%= params[:controller].titleize %></h2>
  </div>
  <hr>
</div>

<div class='small-10 small-centered medium-8 large-6 columns text-center'>
  <%= form_tag transactions_path do %>
    <%= render 'customer_form' unless current_user.has_shipping_address? %>
    <br>
    <p>Please enter your payment details:</p>
    <div id='payment-form'></div>
    <br>
    <%= submit_tag "Pay #{current_order.cart_total}$", class: 'button' %>
  <%end%>
</div>

<script src="https://js.braintreegateway.com/js/braintree-2.20.0.min.js"></script>
<script>
  var clientToken = "<%= @client_token %>";

  braintree.setup(clientToken, "dropin", {
    container: "payment-form",
    paypal: {
      singleUse: false,
      currency: 'USD',
      locale: 'en_us'
    },
    dataCollector: {
      paypal: true  // Enables fraud prevention
    }
  });
</script>