config/routes.rb
OnlineStore::Application.routes.draw do
  # Devise authenticated routes
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
    controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # Devise Login
  # as :user do
  #   get 'login' => 'devise/registrations#new', :as => 'new_user_registration'
  # end

  # Devise Scopes
  devise_scope :user do

    # Authenticated root
    authenticated :user do
      root :to => 'products#index', as: :authenticated_root
    end

    # Unauthenticated root
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end

    # Omniauth sign_out
    # delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  authenticate :user do
    resources :users, only: [:show, :edit] do
      get 'shipping_detail', to: 'users#shipping_detail', as: :shipping_detail
      resources :addresses
    end
  end

  resources :products do

  end

  get 'inventory', to: 'products#inventory', as: :inventory

  resources :order_items

  resources :transactions, only: [:new, :create]
  resources :purchases, only: [:show]
  resource :cart, only: [:show]

  namespace :admin do
    resources :users
    # resources :addresses
    resources :categories
    # resources :credit_cards
    resources :orders
    resources :order_items
    resources :products
    resources :purchases
    # resources :shippers
    # resources :suppliers

    root to: "users#index"
  end

end

app/views/layouts/_alerts.html.erb
<% flash.each do |name, msg| %>
  <%# <% if msg.is_a?(String) %>
    <div class="flash-msg callout round <%= name.to_s == 'notice' ? 'success' : 'alert' %>" data-closable>
      <%= content_tag :div, msg %>
      <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <%# <% end %>
<% end %>

app/views/layouts/_cart_items.html.erb
<%= link_to cart_path, class: 'button' do %>
  <i class='fi-shopping-cart'></i> Cart ( <span class='cart-count'><%= user_signed_in? ? current_order.cart_count : 0 %></span> )
<% end %>

app/views/layouts/_categories.html.erb
<div class='large-3 columns' data-sticky-container>
  <div class='sticky' data-sticky data-anchor='categories' data-sticky-on='large' data-margin-top='0'>
    <ul class='vertical menu' data-accordion-menu>
      <% @categories.each do |category| %>
        <li class=''>
        <%= link_to category.name, products_path(category: category.id) %>
        <ul class='menu vertical nested'>
          <% category.subcategories.each do |subcategory| %>
            <li><%= link_to subcategory.name, products_path(category: subcategory.id) %></li>
          <% end %>
        </ul>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_flashes.html.erb
<%# <% if flash.any? %>

<% flash.each do |name, msg| %>
  <%# <% if msg.is_a?(String) %>
    <div class="flash-msg callout round <%= name.to_s == 'notice' ? 'success' : 'alert' %>" data-closable>
      <%= content_tag :div, msg %>
      <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <%# <% end %>
  <%# <% end %>
<% end %>

app/views/layouts/_header.html.erb
<div class='row'>
  <nav class='top-bar'>

  <div class='top-bar-left'>
    <ul class='menu no-bullet'>
      <li class=''>
      <%= link_to authenticated_root_path do %>
        <i class='fi-shopping-cart'></i> <%= Rails.application.class.parent_name.titleize %>
      <% end %>
      </li>
      <li><%= link_to 'Products', products_path %></li>
      <li><%= link_to 'Orders', order_items_path %></li>
      <%# <li><%= link_to 'Shipping', user_shipping_detail_path(current_user) %></li>
      <li><%= link_to 'Admin', admin_root_path if current_user.present? && current_user.admin? %></li>
    </ul>
  </div>

  <div class='top-bar-right'>
    <ul class='menu'>
      <% if user_signed_in? %>
        <li class='dropmenu'>
          <ul class='dropdown menu' data-dropdown-menu>
            <li><%= link_to image_tag(current_user.avatar.url(:small), class: 'avatar'), user_path(current_user) %>
              <ul class='menu'>
                <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
              </ul>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to 'Register', new_user_registration_path %></li>
        <li><%= link_to 'Login', new_user_session_path %></li>
      <% end %>
        <li><%= render 'layouts/cart_items' %></li>
    </ul>
  </div>

  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Online Store" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class='row full-min-height'>
      <%= render 'layouts/flashes' %>
      <%= yield %>
    </div>

  </body>
</html>